Repository jaoafa/jaoweb-docs, pull requests merged in 2021-11, with the labels that each got.

#93 fix: 運営者情報へのリンク修正
  blog/202110-new-moderator.md
Labels: 修正

#96 fix: CODEOWNERS syntax
  .github/CODEOWNERS
Labels: 修正

#100 fix: プルリク時にlintcheckが走らない問題の修正?
  .github/workflows/markdown-header-check.yml
  .github/workflows/markdown-lintcheck-request.yml
Labels: 修正

#102 feat: mainにマージした際に成果物をプレリリースする ②
  .github/workflows/release.yml
Labels: 修正

#103 feat: markdown-header-checkで執筆者スラッグとカテゴリスラッグを確認する
  .github/scripts/.gitignore
  .github/scripts/markdown-header.js
  .github/scripts/markdown-header.ts
  .github/scripts/package.json
  .github/scripts/tsconfig.json
  .github/workflows/markdown-header-check.yml
Labels: 改善

#104 fix: markdown header checkのバグ修正
  .github/scripts/package.json
  .github/workflows/markdown-header-check.yml
  .github/workflows/release.yml
Labels: 修正

#95 Windowsアプリ版Minecraft Launcherにプロファイルを移行する方法
  blog/how-to-microsoft-minecraft-launcher-installations-migration.md
Labels: 新規

#94 feat: #88 自動切断後、再接続した場合の処理について追加
  server/rules/discord.md
Labels: 改善

#106 feat: プルリク時、ページプレビュー画像をポストするように
  .github/gen-page-preview/.gitignore
  .github/gen-page-preview/main.spec.ts
  .github/gen-page-preview/package.json
  .github/gen-page-preview/playwright.config.ts
  .github/markdown-header-check/.gitignore
  .github/markdown-header-check/markdown-header.ts
  .github/markdown-header-check/package.json
  .github/markdown-header-check/tsconfig.json
  .github/workflows/generate-page-preview-image.yml
  .github/workflows/markdown-header-check.yml
Labels: 改善
