Repository jaoafa/jaoweb-docs, pull requests merged in 2021-09, with the labels that each got.

#42 文章の細分化・二重表現の解消
  server/guidelines/griefing.md
Labels: documentation

#43 文章の一部修正
  support/inquiry.md
Labels: documentation

#44 HPの各種情報を更新
  blog/202108event.md
  blog/join-discord.md
Labels: 修正

#45 基本方針の一部追加
  server/guidelines/cities.md
Labels: 改善

#47 問い合わせページへのリンクを追加
  server/beginners.md
Labels: 改善

#48 文章の修正
  server/guidelines/broadcasts.md
Labels: 修正

#50 文章の追加
  server/guidelines/cities.md
Labels: 改善

#46 文章の修正
  server/policies/privacy.md
Labels: 改善

#49 免責事項の一部更新
  server/policies/index.md
Labels: 修正, 改善

#51 文章の修正
  support/faq.md
Labels: 修正

#52 爆新地の建築ルールについて更新
  support/faq.md
Labels: 改善

#54 お問い合わせへのリンクを追加
  server/guidelines/index.md
Labels: 改善

#55 サーバ仕様の文章修正・追加
  server/specifications.md
Labels: 修正, 改善

#53 FAQの文章修正
  support/faq.md
Labels: 修正, 改善

#58 チャットなどに関するガイドラインの文章加筆修正
  server/guidelines/communications.md
Labels: 修正, 改善

#56 投票解説ブログ記事の文章加筆修正
  blog/how-to-vote.md
Labels: 改善

#59 fix: markdownlintで発生するエラーの抑制
  blog/202108event.md
Labels: 修正

#60 基本方針の細分化・処罰対応の根拠追加・その他文章の修正
  server/policies/bans.md
Labels: 修正, 改善

#57 お問い合わせページの文章加筆修正
  support/inquiry.md
Labels: 修正, 改善

#61 文章の細分化・リンクの追加
  server/beginners.md
Labels: 修正, 改善

#62 更新日時の更新忘れ
  server/guidelines/communications.md
Labels: 修正

#63 「迷惑行為の対応に関するガイドライン」文章の加筆・修正
  server/guidelines/griefing.md
Labels: 修正, 改善

#66 「チャットに関するガイドライン」文章の修正
  server/guidelines/communications.md
Labels: 改善

#67 方針・議決権について加筆修正
  server/policies/index.md
Labels: 修正, 改善

#68 基本方針の明確化
  server/policies/bans.md
Labels: 修正, 改善

#69 README.mdの変更・CODEOWNERSの設定
  .github/CODEOWNERS
  README.md
Labels: 改善

#70 「お問い合わせ」ページの修正
  support/inquiry.md
Labels: 修正

#71 サブアカウントに関する方針の加筆
  server/rules/discord.md
Labels: 修正, 改善

#72 文章の修正
  server/rules/discord.md
Labels: 修正

#74 文章の修正
  server/profiles.md
Labels: 修正

#75 server/index.md の作成
  server/index.md
Labels: 新規

#73 文章の修正
  server/rules/discord.md
Labels: 修正

#77 Community Regularの項目を追加
  server/policies/permissions.md
Labels: 新規

#80 Discordのアカウント管理について追記
  blog/discord-two-factor.md
  server/rules/discord.md
Labels: 修正, 新規, 改善

#82 各種ページの修正
  blog/skin-change.md
  server/guidelines/griefing.md
  server/policies/bans.md
  server/rules/discord.md
  server/specifications.md
  support/faq.md
Labels: 修正

#83 Discord関連のルールについて追記
  server/rules/index.md
Labels: 改善

#86 HPルール項目 文章の修正
  server/beginners.md
  server/profiles.md
  server/rules/discord.md
  server/rules/index.md
  server/specifications.md
Labels: 修正

#87 HPサポート項目 文章の修正
  support/faq.md
  support/inquiry.md
Labels: 修正

#85 HP方針項目 文章の修正
  server/policies/bans.md
  server/policies/index.md
  server/policies/permissions.md
  server/policies/privacy.md
Labels: 修正
