Repository jaoafa/jaoweb-docs, pull requests merged in 2021-04, with the labels that each got.

#21 fix: markdownlint error
  .github/workflows/markdown-lintcheck-push.yml
  .markdownlint.jsonc
  server/policies/permission.md
  support/faq.md
Labels: linterrorfix

#24 撮影・動画配信に関するガイドラインの文章を変更
  server/guidelines/broadcasts.md
Labels: documentation

#27 細かい修正
  server/guidelines/cities.md
Labels: bug

#29 「WorldEditCUIの導入解説」を1.16.5向けにリライト
  blog/worldeditcui-commentary.md
Labels: bug

#30 「Discordで二段階認証をする方法」の画像サイズを修正
  blog/discord-two-factor.md
Labels: fix
