Repository jaoafa/jaoweb-docs, pull requests merged in 2022-08, with the labels that each got.

#170 「プライバシーポリシー」について、文章の修正など
  server/policies/privacy.md
Labels: 修正, 改善

#171 Ban方針について、VBan時の他サービス利用制限について追加
  server/policies/bans.md
Labels: 改善

#177 ページ「サーバ仕様」内コマンド一覧を更新
  server/specifications.md
Labels: 修正

#175 Discordサーバのルールページについて、「jao Minecraft Server独自のDiscordルールである」旨を追記
  server/rules/discord.md
Labels: 改善

#184 "LimitedVerified"の解説記事を固有のページに移動
  server/guidelines/cities.md
  server/policies/limitedverified
  server/policies/permissions.md
  support/faq.md
Labels: 新規, 改善

#185 LimitedVerifiedの解説ページにおいて、拡張子".md"の追加
  server/policies/limitedverified.md
Labels: 修正

#172 なんかいろいろあったけど、FAQの質問を大まかに分類
  support/faq.md
Labels: 改善

#180 「サーバ仕様」ページの情報修正
  server/specifications.md
Labels: 修正, 改善

#182 /support/関連のページにおける情報更新
  support/faq.md
  support/index.md
  support/inquiry.md
Labels: 改善

#187 fix: markdown style
  server/specifications.md
Labels: 修正

#189 Readme.mdの情報を更新
  README.md
  server/policies/limitedverified.md
  support/faq.md
Labels: 修正

#190 fix:Webサイトにおけるリンク切れやリンク間違いの修正
  blog/202108event.md
  blog/worldeditcui-commentary.md
Labels: 修正

#192 2022年8月イベント告知ページの情報を更新
  blog/202208event.md
Labels: 修正
