Repository jaoafa/jaoweb-docs, pull requests merged in 2022-03, with the labels that each got.

#127 feat: 「システムによって禁止されている行為」で、記載内容が一部であることを明文化
  server/rules/index.md
Labels: 改善

#130 「爆新地」の表記を「中央市」へ変更。その他文章の微調整など。
  blog/202202-server-restart.md
  blog/worldguard-commentary.md
  server/guidelines/cities.md
  server/specifications.md
  support/faq.md
Labels: 修正, 改善

#140 feat: ブログ記事「Fabricの導入解説」を追加
  blog/fabric-commentary.md
Labels: 新規
