Repository jaoafa/jaoweb-docs, pull requests merged in 2022-07, with the labels that each got.

#165 feat: 2022年08月イベントに関するブログ記事
  blog/202208event.md
Labels: 新規

#169 fix(202208event): Mod名の修正
  blog/202208event.md
Labels: 修正

#167 club.jaoafa.comのパスワードを忘れた際の対処法を追記
  blog/request-cities.md
  server/guidelines/cities.md
  support/faq.md
Labels: 改善
