Repository jaoafa/jaoweb-docs, pull requests merged in 2022-05, with the labels that each got.

#143 Limited Verifiedについての記事・記述を追加
  blog/limited-verified.md
  server/policies/permissions.md
  support/faq.md
Labels: 新規, 改善

#152 「爆新地」の表記を「中央市」に変更
  blog/worldguard-commentary.md
  server/beginners.md
  server/guidelines/cities.md
  server/specifications.md
Labels: 修正, 改善

#149 チャットガイドラインについて、表記における「定義」を修正
  server/guidelines/communications.md
Labels: 修正, 改善

#146 文章の修正
  blog/limited-verified.md
Labels: 改善

#153 「サーバ停止のお知らせ」の記事について、情報の更新
  blog/202112-server-stop.md
Labels: 修正, 改善

#138 fix: .gitignoreにblog/authors.json と blog/categories.json を追加
  .gitignore
Labels: 修正

#150 Discordの二段階認証を解説するブログ記事において、情報の更新
  blog/discord-two-factor.md
Labels: 修正, 改善

#147 「撮影・動画配信に関するガイドライン」における、基本方針の策定
  server/guidelines/broadcasts.md
Labels: 修正, 改善

#144 サイト内のページについて、軽微な修正
  blog/limited-verified.md
  server/beginners.md
  server/guidelines/broadcasts.md
  server/guidelines/communications.md
  server/guidelines/griefing.md
  server/guidelines/railways.md
  server/policies/bans.md
  server/policies/permissions.md
  server/specifications.md
  support/faq.md
Labels: 修正, 改善
